### ISSUE TITLE
node-gyp rebuild fails using gcc 4.4 with Node 0.12: ISO C++ forbids in-class initialization of non-const static member

### ISSUE THREAD

**Issue by jhecking** [aerospike/aerospike-client-nodejs#131]
Node 4.x and later requires at least GCC 4.8 to build native add-ons. But with Node 0.12 the module should still compile using GCC 4.4. However some recent changes introduced an incompatibility that results in a compile time error:

```
../src/main/client/job_info.cc:38: warning: ISO C++ forbids initialization of member ‘param_err’
../src/main/client/job_info.cc:38: warning: making ‘param_err’ static
../src/main/client/job_info.cc:38: error: ISO C++ forbids in-class initialization of non-const static member ‘param_err’
```

This should be fixed.

Full npm install log:

```
[vagrant@localhost aerospike]$ npm install aerospike
-
> aerospike@2.0.4 install /home/vagrant/aerospike/node_modules/aerospike
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/vagrant/aerospike/node_modules/aerospike/build'
  TOUCH binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
  ACTION binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
which: no lsb_release in (/home/vagrant/.nvm/versions/node/v0.12.14/lib/node_modules/npm/bin/node-gyp-bin:/home/vagrant/aerospike/node_modules/aerospike/node_modules/.bin:/home/vagrant/aerospike/node_modules/.bin:/home/vagrant/.nvm/versions/node/v0.12.14/bin:/home/vagrant/.nvm/versions/node/v0.12.14/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/vagrant/bin)
info: downloading 'http://www.aerospike.com/download/client/c/4.0.4/artifact/el6' to '/home/vagrant/aerospike/node_modules/aerospike/aerospike-client-c/package/aerospike-client-c.tgz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30.7M  100 30.7M    0     0  2486k      0  0:00:12  0:00:12 --:--:-- 3371k
info: extracting 'aerospike-client-c-4.0.4.el6.x86_64/aerospike-client-c-libuv-devel-4.0.4-1.el6.x86_64.rpm' from 'aerospike-client-c.tgz'
info: extracting files from 'aerospike-client-c-4.0.4.el6.x86_64/aerospike-client-c-libuv-devel-4.0.4-1.el6.x86_64.rpm'
16040 blocks

CHECK
   [✓] /home/vagrant/aerospike/node_modules/aerospike/aerospike-client-c/package/usr/lib/libaerospike.a
   [✓] /home/vagrant/aerospike/node_modules/aerospike/aerospike-client-c/package/usr/include/aerospike/aerospike.h
   [✓] /home/vagrant/aerospike/node_modules/aerospike/aerospike-client-c/package/opt/aerospike/client/sys/udf/lua/aerospike.lua

  TOUCH Release/obj.target/aerospike-client-c.stamp
  CXX(target) Release/obj.target/aerospike/src/main/aerospike.o
  CXX(target) Release/obj.target/aerospike/src/main/client.o
  CXX(target) Release/obj.target/aerospike/src/main/query.o
  CXX(target) Release/obj.target/aerospike/src/main/scan.o
  CXX(target) Release/obj.target/aerospike/src/main/async.o
  CXX(target) Release/obj.target/aerospike/src/main/client/apply_async.o
  CXX(target) Release/obj.target/aerospike/src/main/client/batch_exists.o
  CXX(target) Release/obj.target/aerospike/src/main/client/batch_get.o
  CXX(target) Release/obj.target/aerospike/src/main/client/batch_select.o
  CXX(target) Release/obj.target/aerospike/src/main/client/batch_read_async.o
  CXX(target) Release/obj.target/aerospike/src/main/client/cluster.o
  CXX(target) Release/obj.target/aerospike/src/main/client/exists_async.o
  CXX(target) Release/obj.target/aerospike/src/main/client/get_async.o
  CXX(target) Release/obj.target/aerospike/src/main/client/info.o
  CXX(target) Release/obj.target/aerospike/src/main/client/job_info.o
../src/main/client/job_info.cc:38: warning: ISO C++ forbids initialization of member ‘param_err’
../src/main/client/job_info.cc:38: warning: making ‘param_err’ static
../src/main/client/job_info.cc:38: error: ISO C++ forbids in-class initialization of non-const static member ‘param_err’
make: *** [Release/obj.target/aerospike/src/main/client/job_info.o] Error 1
rm binding_gyp_aerospike_client_c_target_run_scripts_aerospike_client_c_sh.intermediate
make: Leaving directory `/home/vagrant/aerospike/node_modules/aerospike/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vagrant/.nvm/versions/node/v0.12.14/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
gyp ERR! System Linux 2.6.32-573.el6.x86_64
gyp ERR! command "node" "/home/vagrant/.nvm/versions/node/v0.12.14/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/aerospike/node_modules/aerospike
gyp ERR! node -v v0.12.14
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 2.6.32-573.el6.x86_64
npm ERR! argv "/home/vagrant/.nvm/versions/node/v0.12.14/bin/node" "/home/vagrant/.nvm/versions/node/v0.12.14/bin/npm" "install" "aerospike"
npm ERR! node v0.12.14
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! aerospike@2.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aerospike@2.0.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the aerospike package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aerospike
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls aerospike
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/aerospike/npm-debug.log
```
