### ISSUE TITLE
Node js client dyld: Symbol not found _OPENSSL_add_all_algorithms_noconf

### ISSUE THREAD

**Issue by prasanthig** [aerospike/aerospike-client-nodejs#378]
Hi, 

I am trying to connect to aerospike from node.js server running on Mac and I receive the below error. I was able to connect to the same aerospike cluster from a Java application running on the same Mac.  

dyld: Symbol not found: _OPENSSL_add_all_algorithms_noconf
  Referenced from: ~/aerospike-nodejs/node_modules/aerospike/build/Release/aerospike.node
  Expected in: flat namespace

I tried with the following LibreSSL 3.1.3, LibreSSL 2.8.3, OpenSSL 1.1.1g  21 Apr 2020. Can you please provide details on how the nodejs client is using openssl and suggestions on how I can resolve this error.

**Comment by PullKit26** [comment]
+1

**Comment by jhecking** [comment]
OpenSSL 1.1.1g should be supported, as that's what I'm using as well. If you have both OpenSSL and LibreSSL installed, maybe the linker resolves the library dependency to LibreSSL? I have never tried using the client with LibreSSL before.

The SSL/TLS library is not used by the Node.js library itself. The Node.js client is just a wrapper around the Aerospike C client SDK. The C client requires OpenSSL both to support TLS encrypted connections to the (Enterprise) server, but more importantly to calculate the key digest, which is done using the RIPEMD160 hash function provided by OpenSSL.

**Comment by DomPeliniAerospike** [comment]
Answer is accurate, Client should work with openssl@1.1.  Most likely LibreSSL was linked rather than Openssl.  Closing now.

**Comment by DomPeliniAerospike** [comment]
Feel free to reopen if additional troubleshooting is needed.
