### ISSUE TITLE
Version 3.10.0 won't build with Node 12.2

### ISSUE THREAD

**Issue by aknuds1** [aerospike/aerospike-client-nodejs#296]
Version 3.10.0 won't build with Node v12.2.0 on OS X:

```
CHECK
   [✓] /Users/arve/Projects/hapi-cache-plugin/node_modules/aerospike/aerospike-client-c/package/usr/local/lib/libaerospike.a
   [✓] /Users/arve/Projects/hapi-cache-plugin/node_modules/aerospike/aerospike-client-c/package/usr/local/include/aerospike/aerospike.h

  TOUCH Release/obj.target/aerospike-client-c.stamp
  CXX(target) Release/obj.target/aerospike/src/main/aerospike.o
../src/main/aerospike.cc:102:6: error: variable has incomplete type 'void'
void Aerospike(Handle<Object> exports, Handle<Object> module)
     ^
../src/main/aerospike.cc:102:23: error: 'Object' does not refer to a value
void Aerospike(Handle<Object> exports, Handle<Object> module)
                      ^
/Users/arve/.node-gyp/12.2.0/include/node/v8.h:3356:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../src/main/aerospike.cc:102:16: error: use of undeclared identifier 'Handle'
void Aerospike(Handle<Object> exports, Handle<Object> module)
               ^
../src/main/aerospike.cc:102:31: error: use of undeclared identifier 'exports'
void Aerospike(Handle<Object> exports, Handle<Object> module)
                              ^
../src/main/aerospike.cc:102:47: error: 'Object' does not refer to a value
void Aerospike(Handle<Object> exports, Handle<Object> module)
                                              ^
/Users/arve/.node-gyp/12.2.0/include/node/v8.h:3356:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../src/main/aerospike.cc:102:40: error: use of undeclared identifier 'Handle'
void Aerospike(Handle<Object> exports, Handle<Object> module)
                                       ^
../src/main/aerospike.cc:102:55: error: use of undeclared identifier 'module'
void Aerospike(Handle<Object> exports, Handle<Object> module)
                                                      ^
../src/main/aerospike.cc:102:62: error: expected ';' after top level declarator
void Aerospike(Handle<Object> exports, Handle<Object> module)
                                                             ^
                                                             ;
8 errors generated.
make: *** [Release/obj.target/aerospike/src/main/aerospike.o] Error 1
```

**Comment by jhecking** [comment]
@aknuds1, I discovered this issue myself yesterday. I've got a fix in PR #295 and am planning to do another release some time later this week.
